theme: jekyll-theme-cayman
title: Arvin Bhurtun
baseurl: "/Blog"
github_username:      abhurtun
linkedin_username:    arvin-bhurtun
google_plus_username: Arvinhurtun
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
logo: /img/logo.png