title: Hello, world! I'm Arvin Bhurtun
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. Hope you enjoy the read!
permalink: ':title/'
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://abhurtun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Arvin Bhurtun # add your name
author-img: me.jpg # add your photo
about-author: > 
  I am a tech enthusiast who is passionate about solving problems. Always hungry to keep learning. 
  
  I'm a Husband, Father, Developer, Engineering Manager and Teacher!
  
  🔭 I’m currently working as an engineering manger building high performing team!
  🌱 I’m currently learning everything 🤣
  🥅 Goals: Don't be afraid to fail
  ⚡ Fun fact: I love to play badminton, football and am a big foody!# add description
social-twitter: # add your Twitter handle
social-facebook:  # add your Facebook handle
social-github: abhurtun # add your Github handle
social-linkedin: arvin-bhurtun-45001526 # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-atb # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
